### ISSUE TITLE
Inquiry on the Release of EVA Dataset and SAFA Model

### ISSUE THREAD

**Issue by andongBlue** [ku-nlp/video-helpful-MMT#1]
Dear Research Team,

I hope this message finds you well. I recently came across your work on "Video-Helpful Multimodal Machine Translation" and was genuinely impressed by its depth and innovation. The integration of multimodal inputs to aid machine translation presents a remarkable step forward in the domain, and I wholeheartedly appreciate the dedication and expertise that went into this research.

I am eagerly anticipating the release of the EVA dataset and SAFA model as mentioned in your publication. May I kindly inquire about the expected timeframe for their open-source release? Having access to these resources would greatly benefit my research and further understanding of the subject.

Thank you for your time and consideration, and once again, kudos on your commendable work. I look forward to your response.

Warm regards,

**Comment by Liyht** [comment]
Hello @andongBlue,

Apologies for the delayed response, and thank you for your interest in our work. While we're in the process of organizing the model's code, I'm pleased to inform you that the dataset has been successfully organized.

Considering the copyright of the included videos, we're unable to directly provide download links. However, if you're interested in accessing the dataset, please kindly send an email to l763541405@gmail.com. By the way, please include your **academic affiliation** in the email, and we'll respond promptly.

Thank you for your understanding.

Best regards,
